# Generated by Django 5.2.5 on 2025-08-29 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='The min quantity a customer can buy in a single purchse. Defaults to 1', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
