# Generated by Django 5.2.5 on 2025-09-04 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='processing', help_text='The status of the order', max_length=20),
        ),
    ]
