# Generated by Django 5.2.5 on 2025-09-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default='adeb075f-cb2f-46c9-9019-785eed57a536', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
            preserve_default=False,
        ),
    ]
