# Generated by Django 5.2.5 on 2025-08-25 14:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, help_text='Leave as Null for automatic discount', max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed'), ('free_shipping', 'Free shipping'), ('new_user', 'New user discount'), ('first_order', 'First order')], default='fixed', help_text='Choose the type of discount', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('total_usage_limit', models.PositiveIntegerField(null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('per_customer_limit', models.PositiveIntegerField(null=True)),
                ('min_amount', models.PositiveIntegerField(default=0, help_text='Minimum purchase amount the discount can be applied to')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='discounts', to='products.category')),
                ('products', models.ManyToManyField(related_name='discounts', to='products.product')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
